name: API Automation Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "00 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Run Tests
        run: mvn clean test -Denv=suite -X

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Logs
          path: logs/

      - name: Publish Test Report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: TestNG Results
          path: target/surefire-reports/junitreports/TEST-*xml
          reporter: java-junit

      - name: Setup Allure History
        uses: actions/checkout@v4.2.2
        if: always()
        continue-on-error: true
        with:
          ref: dev
          path: dev

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.11
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history

      - name: Publish Allure Report
        if: always()
        uses: peaceiris/actions-dev@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: dev
          publish_dir: allure-history
