name: API Automation Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "00 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Run Tests
        run: mvn clean test -Denv=suite -X

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Logs
          path: logs/

      - name: Publish Test Report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: TestNG Results
          path: target/surefire-reports/junitreports/TEST-*xml
          reporter: java-junit
          
      - name: Generate Allure report
        run: mvn allure:report

      - name: Upload Allure Report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
