name: API Test Framework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "00 18 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Run Tests
        run: mvn clean test -Denv=suite -X

      - name: Install Allure
        run: npm install -g allure-commandline --unsafe-perm=true

      - name: Generate Allure Report
        if: always()
        run: |
          if [ -d target/allure-results ] && [ "$(ls -A target/allure-results)" ]; then
            allure generate target/allure-results --clean -o target/allure-report
          else
            echo "No Allure results found, skipping report generation."
          fi

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Allure Report
          path: target/allure-report

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Logs
          path: logs/

      - name: Publish Test Report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: TestNG Results
          path: target/surefire-reports/junitreports/TEST-*xml
          reporter: java-junit